### ISSUE TITLE
How to run on Custom data?

### ISSUE THREAD

**Issue by aniket-gupta1** [TQTQliu/MVSGaussian#10]
Hey, 

thanks for your amazing work. I was wondering how can I run your method on the output from Colmap?

Basically I have data in the following format:
data -- images/
        -- sparse -- 0 -- cameras.bin, images.bin, points3D.bin

**Comment by TQTQliu** [comment]
Hello, we have re-uploaded a friendlier version of the [demo](https://github.com/TQTQliu/MVSGaussian?tab=readme-ov-file#-demo-custom-data), which only requires multi-view images.

**Comment by henrypearce4D** [comment]
@TQTQliu  Our custom dataset is already pre-prepared in the format that @aniket-gupta1 described above for use with the original gaussian splatting code. 

Can the colmap model files we already have;
```
images/
sparse/0/cameras.bin, images.bin, points3D.bin
```

be used directly with your code, without having to run the colmap process again or is running colmap a requirement to get extra information that your code requires - such as for the depth ranges?

**Comment by henrypearce4D** [comment]
I ran imgs2poses.py on my custom data set and it did find the existing colmap model files and created a poses_bounds.npy.

I had to do some edits on the mvsgs.py because my camera names are different than the example.

**Comment by TQTQliu** [comment]
@henrypearce4D 
Hello, I understand your request. Re-runing colmap is not required, we added some explanations [here](https://github.com/TQTQliu/MVSGaussian#-demo-custom-data).
