### ISSUE TITLE
How can I render a visualized scene demo？

### ISSUE THREAD

**Issue by SorryGeats** [TQTQliu/MVSGaussian#20]
How can I render a visualized scene demo from the trained results, not just perform new perspective synthesis？

**Comment by TQTQliu** [comment]
Just add `save_video True`, like:
```
python run.py --type evaluate --cfg_file configs/mvsgs/colmap_eval.yaml test_dataset.data_root examples/scene1 save_video True
```

**Comment by SorryGeats** [comment]
OK，I forgot the opration right now，and thanks for your assistance.
