### ISSUE TITLE
depth

### ISSUE THREAD

**Issue by shaonian123daly** [TQTQliu/MVSGaussian#28]
你好，作者！这是一篇非常棒的工作。
![}HE}$NKSI)S9GCE4M)3H%DJ](https://github.com/user-attachments/assets/a27ab98a-9d71-4251-bf38-7321e361a0fd)
![}HE}$NKSI)S9GCE4M)3H%DJ](https://github.com/user-attachments/assets/3c0e8b53-023a-4541-8d59-a6cdb039fd51)
我想请教下，pipeline里的最终获得的深度图，是位于network.py文件中第92行的depth吗？
如果不是，不知能否指导下mvs部分最终得到的深度图位于哪里，万分感谢

**Comment by shaonian123daly** [comment]
![_ XM5V$AHH$ZJJTQE87%HDL](https://github.com/user-attachments/assets/f259c67f-a01c-4ebc-81d4-f74831a5a5e1)

**Comment by TQTQliu** [comment]
您好，您说的depth的位置是正确的，当i=1,也就是fine stage的depth是MVS最终估计的深度，同时也可以参考深度可视化的代码，在[这里](https://github.com/TQTQliu/MVSGaussian/blob/aa5e786c865858f42c7942edd931cc3b79825628/lib/networks/mvsgs/network.py#L155-L162)。
