### ISSUE TITLE
Where can I find the .ply file for observing the 3D Scene?

### ISSUE THREAD

**Issue by ZhenyuSun-Walker** [TQTQliu/MVSGaussian#31]
Hello Sir, would you mind telling me where does the .ply file save? I 'd like to use the gaussian-splatting viewer to observe the scene that reconstructed by your brilliant method.

**Comment by TQTQliu** [comment]
Hi, thanks for your interest. Please refer to the [script](https://github.com/TQTQliu/MVSGaussian/blob/aa5e786c865858f42c7942edd931cc3b79825628/scripts/mvsgs/llff_ft.sh).

First, run `python run.py --type evaluate --cfg_file configs/mvsgs/llff_eval.yaml save_ply True dir_ply $dir_ply` to obtain the point cloud as initialization, saved in the `mvsgs_pointcloud/scene` folder.
Then, perform per-scene optimization:
```
python lib/train.py  --eval --iterations $iter -s $data_dir/$scene -p $dir_ply
python lib/render.py -c -m output/$scene --iteration $iter -p $dir_ply
python lib/metrics.py -m output/$scene
```
The optimized Gaussian point cloud is saved in the `output/scene/point_cloud/` folder. And you can use the gaussian-splatting viewer to view the optimized Gaussian point cloud.

**Comment by ZhenyuSun-Walker** [comment]
Thank you for your timely reply! I‘ll follow your constructive guidance
!

**Comment by ZhenyuSun-Walker** [comment]
Can I use my own dataset with the `configs/mvsgs/colmap_eval.yaml` as the argument of `--cfg_file`, in the command `python run.py --type evaluate --cfg_file configs/mvsgs/llff_eval.yaml save_ply True dir_ply $dir_ply`? Or you mean the config files serves as initialization of the point clouds, thus it does not affect the final results?

**Comment by TQTQliu** [comment]
Of course, when using your own dataset, you need to specify `--cfg_file` as `configs/mvsgs/colmap_eval.yaml`. 
The above command `python run.py --type evaluate --cfg_file configs/mvsgs/llff_eval.yaml save_ply True dir_ply $dir_ply` is used for LLFF dataset.

**Comment by ZhenyuSun-Walker** [comment]
I fully understand what you mean. Actually I'm also intersted with the outstanding depth estimation method in your work. Maybe later I would set up a new issue and discuss with you about that!
