### ISSUE TITLE
How can I get the Camera Position.json file

### ISSUE THREAD

**Issue by ZhenyuSun-Walker** [TQTQliu/MVSGaussian#32]
Hello Sir, I wonder how can I get the Camera Position.json file? Anticipate for your earliest reply!
![image](https://github.com/user-attachments/assets/d0a168c8-621c-49b8-8e72-6237ab148ad1)

**Comment by TQTQliu** [comment]
Hi, I have not used this online viewer, I recommend using the [original 3DGS viewer](https://github.com/graphdeco-inria/gaussian-splatting?tab=readme-ov-file#interactive-viewers) or [this simplified version](https://github.com/limacv/GaussianSplattingViewer), which only needs Gaussian point cloud (#.ply).

**Comment by ZhenyuSun-Walker** [comment]
Oh, can you tell me how to deal with this error:
![image](https://github.com/user-attachments/assets/12f728e1-5d74-4287-ab46-3ff143676590)

**Comment by TQTQliu** [comment]
We are sorry that the previous code version could not support the per-scene optimization for the custom data, the newly uploaded version has corrected this problem. We updated these two files: `lib/scene/__init__.py` and `lib/scene/dataset_readers.py`. 
And we have added the some instructions in the readme, refer to [here](https://github.com/TQTQliu/MVSGaussian/blob/ade038ec515f83d3e793f6e4e6ebcbcae5344f01/README.md?plain=1#L112-L130).

**Comment by ZhenyuSun-Walker** [comment]
I sincerely appreciate your prompt updates to the code! My training is now in progress!
![image](https://github.com/user-attachments/assets/c993d03b-994c-4366-b13d-8d1b2164ad8d)

**Comment by ZhenyuSun-Walker** [comment]
Another detail I found is that during the training, metric and rendering process, I need to specify the path where `.ply` file stores. I wonder whether I should make these three paths different respectively, or I just use the same path, so that the latest version will simply update the previous one? It is highly appreciated if you can offer me precious advice.  Looking forward to your earliest reply!
![image](https://github.com/user-attachments/assets/f6f88f9d-dfd2-4489-a387-a5c9bcbea134)

**Comment by TQTQliu** [comment]
Please use the same ply file path.

**Comment by ZhenyuSun-Walker** [comment]
Thank you for your timely reply! I'd like to express my sincerest gratitude once again!
