### ISSUE TITLE
About module of decoding gaussian parameters

### ISSUE THREAD

**Issue by ZhenyuSun-Walker** [TQTQliu/MVSGaussian#36]
Hi, sir! How's everything going? I apologize for bothering you again. This time, I would like to ask for your guidance on decoding Gaussian parameters. Could you please let me know where the module code for decoding Gaussian parameters is located in MVSGaussian?

**Comment by TQTQliu** [comment]
Hi, you can find the code for decoding Gaussian parameters [here](https://github.com/TQTQliu/MVSGaussian/blob/84ec6bbb81821848bc7a1defd61b26b9171a8167/lib/networks/mvsgs/gs.py#L9-L114).

**Comment by ZhenyuSun-Walker** [comment]
Thank you！And I noticed that the depth estimation part locates here
![image](https://github.com/user-attachments/assets/3062fe1c-056b-4d07-99e3-b73425da6d59)
But it does not seems right for the depth estimation process in your paper.
Would you mind showing th edepth estimation module?
