### ISSUE TITLE
About depth estimation

### ISSUE THREAD

**Issue by ZhenyuSun-Walker** [TQTQliu/MVSGaussian#37]
Thank you！And I noticed that the depth estimation part locates here
![image](https://github.com/user-attachments/assets/3062fe1c-056b-4d07-99e3-b73425da6d59)
But it does not seems right for the depth estimation process in your paper.
Would you mind showing th edepth estimation module?

**Comment by TQTQliu** [comment]
You're welcome. We used cost volume-based MVS for depth estimates, which you can find [here](https://github.com/TQTQliu/MVSGaussian/blob/84ec6bbb81821848bc7a1defd61b26b9171a8167/lib/networks/mvsgs/network.py#L82-L92).

**Comment by ZhenyuSun-Walker** [comment]
Thanks a lot. I'll check it.
