### ISSUE TITLE
关于所使用的坐标系方向定义提问

### ISSUE THREAD

**Issue by zhangshuoneu** [TQTQliu/MVSGaussian#39]
作者您好，很有趣的工作，也非常感谢代码共享，并且给出了很详细的教程和答疑。我就在您的隔壁武大，马上博一。

在读代码过程中我有一点比较疑惑，在将colmap生成的三个.bin格式的文件保存到poses_bounds.npy时（lib/colmap/poses/pose_utils.py），pose进行了转置，即坐标轴交换，并且作了代码注释从[r, -u, t]到[-u, r, -t]，而不是[r, u, -t]，在Dataset类数据集读取时又进行了pose变换（lib/datasets/colmap/mvsgs.py），似乎是变回了[r, -u, t]，我注意到colmap官方文档指出使用的坐标系定义也是右下前（[r, -u, t]）。这里想问下为什么需要中间这个坐标系变换过程，是poses_bounds.npy文件还有其他用途吗？

**Comment by TQTQliu** [comment]
谢谢您对我们工作的关注，预祝您博士生涯顺利。
您的观察是对的，事实上，我们是用的[llff](https://github.com/Fyusion/LLFF)提供的imgs2poses.py和pose_utils.py文件，
imgs2poses.py的作用是：调用colmap估计相机的参数，在sparse/0/文件夹下生成一些二进制文件：cameras.bin, images.bin, points3D.bin, project.ini，然后读取这些二进制文件，保存成poses_bounds.npy文件。

colmap坐标系方向定义和opencv是一样的，x轴正方向向右R(ight)，y轴正方向向下D(own)，z轴正方向向前(Forward)，也就是RDF。
在pose_utils.py文件load_colmap_data()函数中，会将colmap得到的c2w旋转矩阵中的第一列和第二列互换，第三列乘以负号（X和Y轴调换，Z轴取反），转换为LLFF的DRB坐标系。
在后续dataset加载数据的时候，我们可以根据自己的需求将LLFF的DRB转换成所需要的坐标系。例如NeRF用的是opengl的坐标系，所以转换代码是`poses = np.concatenate([poses[:, 1:2, :], -poses[:, 0:1, :], poses[:, 2:, :]], 1)`, 同时在[这里](https://github.com/yenchenlin/nerf-pytorch/blob/63a5a630c9abd62b0f21c08703d0ac2ea7d4b9dd/load_llff.py#L250)找到。

而我们用的是opencv/colmap坐标系，所以在后续数据加载的时候又转换回来了。

![image](https://github.com/user-attachments/assets/0dbb3a74-bbe8-4670-83cc-3a142997d6c3)

**Comment by zhangshuoneu** [comment]
> 谢谢您对我们工作的关注，预祝您博士生涯顺利。 您的观察是对的，事实上，我们是用的[llff](https://github.com/Fyusion/LLFF)提供的imgs2poses.py和pose_utils.py文件， imgs2poses.py的作用是：调用colmap估计相机的参数，在sparse/0/文件夹下生成一些二进制文件：cameras.bin, images.bin, points3D.bin, project.ini，然后读取这些二进制文件，保存成poses_bounds.npy文件。
> 
> colmap坐标系方向定义和opencv是一样的，x轴正方向向右R(ight)，y轴正方向向下D(own)，z轴正方向向前(Forward)，也就是RDF。 在pose_utils.py文件load_colmap_data()函数中，会将colmap得到的c2w旋转矩阵中的第一列和第二列互换，第三列乘以负号（X和Y轴调换，Z轴取反），转换为LLFF的DRB坐标系。 在后续dataset加载数据的时候，我们可以根据自己的需求将LLFF的DRB转换成所需要的坐标系。例如NeRF用的是opengl的坐标系，所以转换代码是`poses = np.concatenate([poses[:, 1:2, :], -poses[:, 0:1, :], poses[:, 2:, :]], 1)`, 同时在[这里](https://github.com/yenchenlin/nerf-pytorch/blob/63a5a630c9abd62b0f21c08703d0ac2ea7d4b9dd/load_llff.py#L250)找到。
> 
> 而我们用的是opencv/colmap坐标系，所以在后续数据加载的时候又转换回来了。
> 
> ![image](https://private-user-images.githubusercontent.com/92019012/360730647-0dbb3a74-bbe8-4670-83cc-3a142997d6c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODAyMzYsIm5iZiI6MTcyNDM3OTkzNiwicGF0aCI6Ii85MjAxOTAxMi8zNjA3MzA2NDctMGRiYjNhNzQtYmJlOC00NjcwLTgzY2MtM2ExNDI5OTdkNmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAyMjUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYjVjZWRhNmQ1NDQ3ZmI0MDdjMWJkNmFjNzA2OGVlNWRjMTI5NGI4OTc3MjZhNTFkMTc5ZjRkNzJiZWYxMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Kb1zq-_sMZomthg_8Db0IK1BG-ullR7T-LOydnVNeQ)

非常感谢您的快速回复，详细解释，还配上图形示意，太周到了，也祝你研途顺利！

**Comment by zhangshuoneu** [comment]
是否方便加个微信，哈哈，这样请教问题就方便很多啦

**Comment by TQTQliu** [comment]
我的微信号是: liu1466847018
