### ISSUE TITLE
代码运行时遇到问题！

### ISSUE THREAD

**Issue by yjl010228** [TQTQliu/MVSGaussian#47]
### 代码运行时遇到问题！
我在nerf_llff数据集上进行推理。
在逐场景优化时，当我运行`python lib/train.py  --eval --iterations <iter> -s examples/scene1 -p <path to save ply>`后，遇到了以下的错误：
Optimizing ./output/fern
Output folder: ./output/fern
Tensorboard not available: not logging progress
Reading camera 1/20Traceback (most recent call last):
  File "lib/train.py", line 236, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, init_ply=args.init_ply)
  File "lib/train.py", line 67, in training
    scene = Scene(dataset, gaussians, init_ply=init_ply)
  File "/home/amax/Public/yjl/MVSGaussian-main/lib/scene/__init__.py", line 44, in __init__
    scene_info = sceneLoadTypeCallbacks["LLFF"](args.source_path, init_ply=init_ply, video=video)
  File "/home/amax/Public/yjl/MVSGaussian-main/lib/scene/dataset_readers.py", line 163, in readColmapSceneInfo_LLFF
    path=path, rgb_mapping=rgb_mapping)
  File "/home/amax/Public/yjl/MVSGaussian-main/lib/scene/dataset_readers.py", line 110, in readColmapCameras_LLFF
    image_path = rgb_mapping[idx]
IndexError: list index out of range
我该如何解决它？提前感谢！

**Comment by yjl010228** [comment]
### 这是我的数据集和获得的mvsgs_pointcloud
![1725606017251](https://github.com/user-attachments/assets/02e0a6e6-67fa-43c6-94cc-bdfc0a61b471)
![1725606000877(1)](https://github.com/user-attachments/assets/4dc9973a-1bea-4001-b5db-11fe13881744)

**Comment by TQTQliu** [comment]
You can try modifying this line：
https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/scene/dataset_readers.py#L159
to
`reading_dir = 'images'`

**Comment by yjl010228** [comment]
> You can try modifying this line：
> 
> https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/scene/dataset_readers.py#L159
> 
> 
> to
> `reading_dir = 'images'`

Wow！It works!Thanks very much to you!
