### ISSUE TITLE
question about rendering of nerf_llff datasets！

### ISSUE THREAD

**Issue by yjl010228** [TQTQliu/MVSGaussian#48]
**Respect author！**
I directly used the nerf_llff dataset you provided,then I run the generalizable model to obtain the point cloud and run the 3DGS optimization to obtain the optimized Gaussian point cloud.When I run `python lib/render.py -c -m output/scene1 --iteration <iter> -p <path to save ply>` `python lib/metrics.py -m output/scene1` to get the renders,I find the results a little poor.
Like the room:
![1725695128324](https://github.com/user-attachments/assets/474e7c79-a155-445f-9f31-4faf3cdb9622)
Thank you in advance for taking the time out of your busy schedule to answer my question！

**Comment by TQTQliu** [comment]
Hi, according to the information you provided, I don't see what went wrong, could you also provide me with the screenshot of training, focusing on whether the point cloud was loaded as the initialization.

**Comment by yjl010228** [comment]
> Hi, according to the information you provided, I don't see what went wrong, could you also provide me with the screenshot of training, focusing on whether the point cloud was loaded as the initialization.

Thank you very much for your reply.The details are as folows:
I directly used the room of nerf_llff dataset you provided,as this:
![room](https://github.com/user-attachments/assets/85de7aa4-753a-4126-9d43-6a2a0fbe0f83)
Then,I run the generalizable model to obtain the point cloud
`python run.py --type evaluate --cfg_file configs/mvsgs/colmap_eval.yaml test_dataset.data_root nerf_llff/room save_ply True dir_ply mvsgs_pointcloud`
result as this:
![point](https://github.com/user-attachments/assets/1eb96a5a-7481-4abe-8b73-d24267f7d297)
Finally,I run the 3DGS optimization to get the output,the result is as follows:
`python lib/train.py  --eval --iterations 2500 -s  nerf_llff/room -p mvsgs_pointcloud`
![1725759691018](https://github.com/user-attachments/assets/e79c134f-f476-43b6-a426-14e7f03ecf1c)

I run the following commands to synthesize target views and calculate metrics
`python lib/render.py -c -m output/room --iteration 2500 -p mvsgs_pointcloud`
`python lib/metrics.py -m output/room`
and get the final metrics. Additonally the pretrained model is existing in the code file:
![1725760060161](https://github.com/user-attachments/assets/e1416ceb-6f4a-496a-bb68-5e74fba46354)
I have hardly done any other operations besides this.Looking forward to your reply again sincerely and If there are any other operations that I haven't explained clearly, please let me know!

**Comment by TQTQliu** [comment]
The command for the first step should be changed to `python run.py --type evaluate --cfg_file configs/mvsgs/llff_eval.yaml test_dataset.data_root nerf_llff test_dataset.scene room save_ply True dir_ply mvsgs_pointcloud`.

The reason you need to use `llff_eval.yaml` instead of `colmap_eval.yaml` is because of [this line](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/datasets/llff/mvsgs.py#L46). The images in the dataset we provided were downsampled by a factor of 4, so the corresponding camera parameters also need to be modified. You can also add this line to the [colmap dataset file](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/datasets/colmap/mvsgs.py#L43) and run it with your original command.

**Comment by yjl010228** [comment]
> The command for the first step should be changed to `python run.py --type evaluate --cfg_file configs/mvsgs/llff_eval.yaml test_dataset.data_root nerf_llff test_dataset.scene room save_ply True dir_ply mvsgs_pointcloud`.
> 
> The reason you need to use `llff_eval.yaml` instead of `colmap_eval.yaml` is because of [this line](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/datasets/llff/mvsgs.py#L46). The images in the dataset we provided were downsampled by a factor of 4, so the corresponding camera parameters also need to be modified. You can also add this line to the [colmap dataset file](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/datasets/colmap/mvsgs.py#L43) and run it with your original command.

This operation works when I add this line `ixts[:, :2] *= 0.25` to the [colmap dataset file](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/datasets/colmap/mvsgs.py#L43) and run it with my original command.
But when I run `python run.py --type evaluate --cfg_file configs/mvsgs/llff_eval.yaml test_dataset.data_root nerf_llff test_dataset.scene room save_ply True dir_ply mvsgs_pointcloud` you provided,it appears error:_AssertionError:Non-existent key: test_dataset.scene._

**Comment by TQTQliu** [comment]
Or you can specify the scene [here](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/configs/mvsgs/llff_eval.yaml#L20-L24):

```
test_dataset:
    data_root: 'nerf_llff_data'
    split: 'test'
    input_h_w: [640, 960]
    input_ratio: 1.
    scene: room
```
And then run:
```
python run.py --type evaluate --cfg_file configs/mvsgs/llff_eval.yaml test_dataset.data_root nerf_llff save_ply True dir_ply mvsgs_pointcloud
```

**Comment by yjl010228** [comment]
> Or you can specify the scene [here](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/configs/mvsgs/llff_eval.yaml#L20-L24):
> 
> ```
> test_dataset:
>     data_root: 'nerf_llff_data'
>     split: 'test'
>     input_h_w: [640, 960]
>     input_ratio: 1.
>     scene: room
> ```
> 
> And then run:
> 
> ```
> python run.py --type evaluate --cfg_file configs/mvsgs/llff_eval.yaml test_dataset.data_root nerf_llff save_ply True dir_ply mvsgs_pointcloud
> ```

ok！Thank you for your helpful assistance！
