### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by Mingqj** [TQTQliu/MVSGaussian#5]
Hi, I'm very interested in your MVSGaussian, and when do you plan to release your code?

**Comment by TQTQliu** [comment]
Thanks for your interest in our work , we are organizing the code now and will release it soon.

**Comment by Mingqj** [comment]
Thank you for your response! I look forward to your open-source code!

**Comment by daiguangzhao** [comment]
Thank you and your team for contributing such excellent work! Looking forward to your open-source code!

**Comment by TQTQliu** [comment]
@daiguangzhao @Mingqj 
Hello, thanks for your recognition of our work, the code has been released.
