### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by Aur1anna** [TQTQliu/MVSGaussian#52]
Hi，thanks for your amazing work!!

When I use run.py to obtain novel views, I have this error: 
OSError: [Errno 24] Too many open files. 

The command all I used:
```
python lib/colmap/imgs2poses.py -s examples/stone_rgb
python run.py --type evaluate --cfg_file configs/mvsgs/colmap_eval.yaml test_dataset.data_root examples/stone_rgb save_video True
```
and more details:
![image](https://github.com/user-attachments/assets/54fbfbcd-ef76-43a3-8071-0b8d9769fa18)

Thanks for your contribution again!! And any help will be appreciated!!

**Comment by TQTQliu** [comment]
Thanks for your kind word!
Actually, I haven't encountered this error yet. 
Do you also get the error when running the data in the example we provided?
Maybe you can try setting num_workers to 0, change that [here](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/configs/mvsgs/dtu_pretrain.yaml#L76).

**Comment by Aur1anna** [comment]
Hi, thank you for your reply! yeah I also get this error when running the example/scene1.
 
After "ulimit -a" I found the "open files (-n)" equals 1024 and I try to fix this by using "ulimit -n 2048". Now it seems good, 60 pictures and video can be saved, but the whole output video is just a black screen.
![{6A043F90-791F-4A5C-97D7-A808FCD3F137}](https://github.com/user-attachments/assets/95fce35f-35b9-4f9b-a069-739a284859c3)
And this happened on both example/scene1 and my stone_rgb dataset.

Maybe all of this is due to an environment issue? But I don't remember any errors during the environment setup process. Anyway I'll try again later.

**Comment by Aur1anna** [comment]
I set up a new env and it just didnt work again. Maybe 60 pictures is considered enough for me :) :) :)

**Comment by TQTQliu** [comment]
Thank you for sharing!
If you want, you can turn 60 images into a video through post-processing.
