### ISSUE TITLE
How many days for training?

### ISSUE THREAD

**Issue by leo-frank** [TQTQliu/MVSGaussian#54]
How many days for training?

**Comment by TQTQliu** [comment]
For training generalizable model, we trained 300 epochs on 4 RTX 3090 gpus, with a batch size of 1 for each GPU, and took approximately 25 hours to complete. 
We also provided training time for different number of gpus and batch sizes in [this table](https://github.com/TQTQliu/MVSGaussian/tree/main?tab=readme-ov-file#train-generalizable-model) for reference

**Comment by leo-frank** [comment]
thanks alot~!
