### ISSUE TITLE
Questions about training the generalized model on my own datasets

### ISSUE THREAD

**Issue by yjl010228** [TQTQliu/MVSGaussian#55]
Respect authors!I want to train the generalized model on my own datasets,but I do not know **what format or files do I need for my dataset**.Otherwise,the DTU datasets confuses me because it has many various files.I am looking forward to your timely reply!Thank you very much in advance!
I know the command is `python train_net.py --cfg_file configs/mvsgs/colmap_eval.yaml train_dataset.data_root examples/scene1 test_dataset.data_root examples/scene1`

**Comment by yjl010228** [comment]
For example, if I have some scenes everyone that have around 20 images、sparse/0 and poses_bounds.npy and how to set up a dataset so that I could successfully train the generalized model.

**Comment by TQTQliu** [comment]
Hi, if you want to train the model on many scenes, you can modify the [dataset file](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/datasets/colmap/mvsgs.py), for details on how to modify, you can refer to the [llff dataset file](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/datasets/llff/mvsgs.py), where you set the scene name [here](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/datasets/llff/mvsgs.py#L31), and you can download the [LLFF dataset](https://drive.google.com/drive/folders/1rciqkjLQEBnoT3lrXWfsJW3s3dHdrV9e?usp=sharing) and refer to its organizational format, like:
```
data
    ├── scene1                   
        ├── images                
        ├── sparse   
                 ├── 0
        ├── poses_bounds.npy
   ├── scene2
    ...
```

**Comment by yjl010228** [comment]
> Hi, if you want to train the model on many scenes, you can modify the [dataset file](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/datasets/colmap/mvsgs.py), for details on how to modify, you can refer to the [llff dataset file](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/datasets/llff/mvsgs.py), where you set the scene name [here](https://github.com/TQTQliu/MVSGaussian/blob/b9a0fdd822dffad73cdcefb5b2120865c1064109/lib/datasets/llff/mvsgs.py#L31), and you can download the [LLFF dataset](https://drive.google.com/drive/folders/1rciqkjLQEBnoT3lrXWfsJW3s3dHdrV9e?usp=sharing) and refer to its organizational format, like:
> 
> ```
> data
>     ├── scene1                   
>         ├── images                
>         ├── sparse   
>                  ├── 0
>         ├── poses_bounds.npy
>    ├── scene2
>     ...
> ```

Thanks for your reply.I see what you mean but what are the specific commands?Because your command like `python train_net.py --cfg_file configs/mvsgs/colmap_eval.yaml train_dataset.data_root examples/scene1 test_dataset.data_root examples/scene1`  looks like it's only for a single scene and I tried to delete `/scene1` above and run the command above.It makes a mistake like `FileNotFoundError: [Errno 2] No such file or directory: './my multi-scenes datasets/images'`

**Comment by TQTQliu** [comment]
Hi, I updated the code and the corresponding readme.

 If you want to train our model on your own dataset, first organize the dataset as follows：
  ```
  data
    ├── scene1                   
        ├── images                
        ├── sparse   
                 ├── 0
        ├── poses_bounds.npy
   ├── scene2
    ...
  ```
  Modify the scenes list [here](https://github.com/TQTQliu/MVSGaussian/blob/47df5632b723d36a78b422370706ea6221c72e8f/lib/datasets/colmap/mvsgs.py#L32) and then execute the following commands:
  ```
  python train_net.py --cfg_file configs/mvsgs/colmap_eval.yaml train_dataset.data_root examples test_dataset.data_root examples
  ```

**Comment by yjl010228** [comment]
> Hi, I updated the code and the corresponding readme.
> 
> If you want to train our model on your own dataset, first organize the dataset as follows：
> 
> ```
> data
>   ├── scene1                   
>       ├── images                
>       ├── sparse   
>                ├── 0
>       ├── poses_bounds.npy
>  ├── scene2
>   ...
> ```
> 
> Modify the scenes list [here](https://github.com/TQTQliu/MVSGaussian/blob/e06a8234381d812c50bb7f7975083ea7a27f77a4/lib/datasets/colmap/mvsgs.py#L32) and then execute the following commands:
> 
> ```
> python train_net.py --cfg_file configs/mvsgs/colmap_eval.yaml train_dataset.data_root examples test_dataset.data_root examples
> ```

It works for me! Thank you very much for your reply and assistance.
