### ISSUE TITLE
关于tnt训练集相机标定的问题

### ISSUE THREAD

**Issue by yyy-boop** [TQTQliu/MVSGaussian#59]
您好！我是一个三维重建小白，我希望模仿您的模型重建tnt训练集的方式来重建我的数据。但是我不理解这些cam.txt文件中的相机参数矩阵代表的含义以及他们是如何获得的。我希望为我的图片数据也制作对应的文件以进行训练，您能给我一些建议吗，非常感谢！
![image](https://github.com/user-attachments/assets/05f503d2-dc79-4ff8-8149-48be217caf5b)

**Comment by TQTQliu** [comment]
您好，extrinsic表示的相机外参[R,t](R是旋转矩阵，t是平移向量），intrinsic表示的是相机内参K=[f_x, 0, c_x; 0, f_y, c_y; 0, 0, 1]，cam.txt文件最后一行是深度范围[depth_min, depth_max]。

关于custom data的相机标定和训练，请参见我们readme的[Demo (Custom Data)部分](https://github.com/TQTQliu/MVSGaussian#-demo-custom-data)。

**Comment by yyy-boop** [comment]
> 您好，extrinsic表示的相机外参[R，t]（R是旋转矩阵，t是平移向量），intrinsic表示的是相机内参K=[f_x， 0， c_x; 0， f_y， c_y; 0， 0， 1]，cam.txt文件最后一行是深度范围[depth_min， depth_max]。
> 
> 关于custom data的相机标定和训练，请参见[readme的Demo （Custom Data）部分](https://github.com/TQTQliu/MVSGaussian#-demo-custom-data)。

能否劳烦您告诉我您在这里说的深度范围代表什么吗？我该如何去获取它呢？
