### ISSUE TITLE
How can I use my own data to train and test?

### ISSUE THREAD

**Issue by gwxxx** [TQTQliu/MVSGaussian#6]

**Comment by henrypearce4D** [comment]
Hi great work, I would love to test on our own datasets.

Could you help with instructions for running training on colmap model files datasets?

\images
\sparse

**Comment by TQTQliu** [comment]
Hi, thanks for your interest in our work.
When using your own data, the  important thing is to obtain the correct format for both intrinsic and extrinsic camera parameters.
 We've added a simple [demo](https://github.com/TQTQliu/MVSGaussian/blob/ae6817432f919fc8e8491a2797f3123119b764a9/README.md?plain=1#L152), hoping that it will be helpful to you. Additionally, you can refer to our dataset files([dtu](https://github.com/TQTQliu/MVSGaussian/blob/main/lib/datasets/dtu/mvsgs.py), [llff](https://github.com/TQTQliu/MVSGaussian/blob/7b1934cc226855ba73ac6df60675c3145d9a92bf/lib/datasets/llff/mvsgs.py), [NeRF Synthetic](https://github.com/TQTQliu/MVSGaussian/blob/7b1934cc226855ba73ac6df60675c3145d9a92bf/lib/datasets/nerf/mvsgs.py), and [Tanks and Temples](https://github.com/TQTQliu/MVSGaussian/blob/7b1934cc226855ba73ac6df60675c3145d9a92bf/lib/datasets/tnt/mvsgs.py)).

**Comment by chenqi13814529300** [comment]
Can you provide a detailed explanation? When reproducing other papers, I used the same solution: Python train.py - s xxxx - m xxxx to obtain the results

**Comment by TQTQliu** [comment]
@chenqi13814529300 
Sorry for the late reply, we will review the README and add as many details as possible. We also welcome your specific suggestions or any questions or problems you encounter when using our code.

**Comment by chenqi13814529300** [comment]
We hope that your code has strong extensibility, as most of us only have data such as/parse and/images, which come from Colmap.

**Comment by TQTQliu** [comment]
@chenqi13814529300  Thanks for your suggestion, we will provide the code for the colmap data format later.

**Comment by TQTQliu** [comment]
Hello, we have re-uploaded a friendlier version of the [demo](https://github.com/TQTQliu/MVSGaussian?tab=readme-ov-file#-demo-custom-data), which only requires multi-view images.
