### ISSUE TITLE
May I give an awkward question

### ISSUE THREAD

**Issue by MSH970515** [TQTQliu/MVSGaussian#61]
Hi, thanks for great work.

How can I adjust the either 3-view or 2-view training details in the cfg code?

I just started exploring this field, so it might seem awkward to you, but I will be waiting for your reply

thanks

**Comment by MSH970515** [comment]
I have another question,
is the number of epochs fixed to 300, regardless of the number of batch size and gpus?

**Comment by TQTQliu** [comment]
Hi, thanks for your interest.

During training, we select 2, 3, and 4 source views as inputs with respective probabilities of 0.1, 0.8, and 0.1, refer [here](https://github.com/TQTQliu/MVSGaussian/blob/2efbe9d51c67fb4e4b7c945265948e611751692a/configs/mvsgs/dtu_pretrain.yaml#L21-L22).
For testing, you can modify the number of input views [here](https://github.com/TQTQliu/MVSGaussian/blob/2efbe9d51c67fb4e4b7c945265948e611751692a/configs/mvsgs/dtu_pretrain.yaml#L23).

Yes, the default number of epochs is set to 300 [here](https://github.com/TQTQliu/MVSGaussian/blob/2efbe9d51c67fb4e4b7c945265948e611751692a/configs/mvsgs/dtu_pretrain.yaml#L66), and the number of iterations per epoch is 1000 [here](https://github.com/TQTQliu/MVSGaussian/blob/2efbe9d51c67fb4e4b7c945265948e611751692a/configs/mvsgs/dtu_pretrain.yaml#L86).

**Comment by MSH970515** [comment]
Thanks!
