### ISSUE TITLE
Questions about rendering weak textures or specular areas

### ISSUE THREAD

**Issue by yjl010228** [TQTQliu/MVSGaussian#63]
Respect author,
I'm looking for suggestions for **weak textures or specular areas** that reduced depth accuracy,resulting in a degraded view quality.For example, in the truck of tnt dataset, it does a good job although the truck scene has weak textures and specular areas.I guess the reason is that there is up to **251** images which makes the sparse point clouds more widely distributed and denser?And do you have any **suggestions** for improving the above issues?

**Comment by hjh530** [comment]
You can try depth regularization, using monocular depth estimation，that can fix weak textures.And about specular areas ，I  also want to know how to solve it.
