### ISSUE TITLE
Model parallel training

### ISSUE THREAD

**Issue by gap705** [TQTQliu/MVSGaussian#69]
Dear author, congratulations on your good work. I want to change MVS-Gaussian to model parallel training (single machine with multiple GPUs). Do you have any suggestions? Thank you.

**Comment by TQTQliu** [comment]
Hi, our code supports multi-gpu training, you can run:

```
python -m torch.distributed.launch --nproc_per_node=4 train_net.py --cfg_file configs/mvsgs/dtu_pretrain.yaml distributed True gpus 0,1,2,3 train.batch_size 1
```

**Comment by gap705** [comment]
Thanks for your reply. Because the images I use are large, the OOM error will occur even if the batch size is 1 for each GPU. So I want to distribute different parts of the network to multiple GPUs. Do you have any suggestions? Thank you.

**Comment by TQTQliu** [comment]
I haven't tried to distribute different parts of the network to multiple GPUs. 
Here are some things that can reduce training momery:
1) modify the input image resolution: https://github.com/TQTQliu/MVSGaussian/blob/49996d865b89664578221d0ea15e62b3a7c9c7fa/configs/mvsgs/colmap_eval.yaml#L17
2) modify the number of input views: 
https://github.com/TQTQliu/MVSGaussian/blob/49996d865b89664578221d0ea15e62b3a7c9c7fa/configs/mvsgs/dtu_pretrain.yaml#L21-L22

To reduce memory consumption, you can modify it to:
```
train_input_views: [2] 
train_input_views_prob: [1] 
```

3) you can also modify the number of sampling points per ray [here](https://github.com/TQTQliu/MVSGaussian/blob/49996d865b89664578221d0ea15e62b3a7c9c7fa/configs/mvsgs/colmap_eval.yaml#L12).

**Comment by gap705** [comment]
Thanks for your reply. I will try these methods, thanks again.
