### ISSUE TITLE
关于流程上一些详细的步骤

### ISSUE THREAD

**Issue by james201011071** [TQTQliu/MVSGaussian#7]
非常感谢这么好的工作的分享，我有个小小的建议：
流程上可以详细些，就是train test的步骤，包括预训练的泛化的模型可以怎么用？非常感谢

**Comment by TQTQliu** [comment]
@james201011071 
Sorry for the late reply, we will review the README and add as many details as possible. We also welcome your specific suggestions or any questions or problems you encounter when using our code.
