### ISSUE TITLE
出现FileNotFoundError: [Errno 2] No such file or directory: 'colmap': 'colmap'报错

### ISSUE THREAD

**Issue by YXyouxi** [TQTQliu/MVSGaussian#73]
作者您好，十分感谢您的开源。我在运行python lib/colmap/imgs2poses.py -s examples/scene1这条命令时，出现了FileNotFoundError: [Errno 2] No such file or directory: 'colmap': 'colmap'报错，请问这是否意味着我需要安装colmap，imgs2poses.py只是执行colmap的文件吗？

**Comment by TQTQliu** [comment]
您好，是的，需要安装colmap，imgs2poses.py是用来执行colmap并整理得到LLFF格式的数据。
