### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by chenll12345** [TQTQliu/MVSGaussian#8]
I utilized the open-source code you provided to run the MVSGaussian model and Unfortunately, under your experimental configuration, training on the DTU dataset for 300 epochs only achieved a performance of 27.58 dB. I noticed that in the code you released, the sampling points for both levels are the same（one sample）, and the rotation network of the Gaussian module has not been unlocked for training (you set it to a fixed value). I am not too sure if the issue lies with my environment or with the code you released. If you could address my questions, I would be extremely grateful.

**Comment by TQTQliu** [comment]
Hi, thanks for your interest in our work. We trained our modol on 4 RTX3090 gpus with batchsize 1. If you train the model on a single gpu and the batchsize is 1, the performance may not as good as using 4 gpus. When using a single gpu, the batchsize should be changed to 4. However, the current code only supports 1 batchsize, and you can modify the code to support multiple batchsize. We'll also upload the updated code in the next few days after we finish our current stuff.

**Comment by TQTQliu** [comment]
@chenll12345 
Hello, we re-updated code which can support [multi-batch training](https://github.com/TQTQliu/MVSGaussian?tab=readme-ov-file#-training), a single 3090 GPU is sufficient to reproduce all of our experimental results.
